### ISSUE TITLE
没看见方法4耶

### ISSUE THREAD

**Issue by Testplayers** [zzliux/assttyys_autojs#1]

**Comment by zzliux** [comment]
您好，仓库主要在gitee进行维护，github仓库仅做备份使用，方法4的issue地址为：<https://gitee.com/zzliux/assttyys_autojs/issues/I148NB>

**Comment by Testplayers** [comment]
> 您好，仓库主要在gitee进行维护，github仓库仅做备份使用，方法4的issue地址为：https://gitee.com/zzliux/assttyys_autojs/issues/I148NB
