### ISSUE TITLE
你好,有没有使用文档诶

### ISSUE THREAD

**Issue by zhang-wangz** [zzliux/assttyys_autojs#13]
如题,有没有使用文档诶, 应该怎么使用

**Comment by zzliux** [comment]
点鸡进群，部分版本或平台的qq可能不支持
[![group:864842180](https://img.shields.io/badge/group-864842180-blue)](https://qm.qq.com/q/H852T6N0OG)

**Comment by zhang-wangz** [comment]
> 点鸡进群，部分版本或平台的qq可能不支持 [![group:864842180](https://camo.githubusercontent.com/1974422bf6be38ac6f4f8daa5cccce8604f88eda824f4616454be6fe3c129356/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f67726f75702d3836343834323138302d626c7565)](https://qm.qq.com/q/H852T6N0OG)

qq显示该群不可加入人或者群设置了不允许加入,手动搜索添加也一样

**Comment by zhang-wangz** [comment]
> 点鸡进群，部分版本或平台的qq可能不支持 [![group:864842180](https://camo.githubusercontent.com/1974422bf6be38ac6f4f8daa5cccce8604f88eda824f4616454be6fe3c129356/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f67726f75702d3836343834323138302d626c7565)](https://qm.qq.com/q/H852T6N0OG)

<img width="342" alt="image" src="https://github.com/zzliux/assttyys_autojs/assets/49056179/7fbf031f-f432-40e2-a7c0-51c8e9fed376">

**Comment by zzliux** [comment]
> 



> > 点鸡进群，部分版本或平台的qq可能不支持 [![group:864842180](https://camo.githubusercontent.com/1974422bf6be38ac6f4f8daa5cccce8604f88eda824f4616454be6fe3c129356/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f67726f75702d3836343834323138302d626c7565)](https://qm.qq.com/q/H852T6N0OG)
> 
> qq显示该群不可加入人或者群设置了不允许加入,手动搜索添加也一样

是搜不了，设置了只能从链接进，pcntqq好像本身就不识别这种不允许被搜索的链接，换手机qq，或者在手机qq使用链接跳进来（ios可能也有点问题）

**Comment by LeisureCheng** [comment]
大佬，IOS和PC都没办法加入q群
