### ISSUE TITLE
新手求教，关于项目apk的提问

### ISSUE THREAD

**Issue by LimingEA** [zzliux/assttyys_autojs#27]
已点stars

**Comment by LimingEA** [comment]
这个项目如何一步一步导出成apk呢，可以简单的出个图文教程吗

**Comment by zzliux** [comment]
1. 首先要一个能用的autojspro，并且vsocde连接上了ajpro
2. 拉取项目源代码
3. 安装依赖: npm install
4. 构建项目: npm run build
5. 将构建的结构保存组autojspro上：ctrl-shift-p后save project
6. 在autojspro上打包

**Comment by LimingEA** [comment]
Auto.js pro打开的时候会闪退，用安卓7的模拟器打开也会闪退，大佬有什么办法吗

**Comment by LimingEA** [comment]
我找到了一个可用的auto.jspro，目前我遇到的问题是我在vscode上下载了Auto.js包，运行服务后将展示出来的连接Auto.jspro的IP地址输入到了autojspro中，目前我已经安装过依赖了npm install，我不知道我的autojspro是否已经连接上vscode，我接下来应该怎么做

**Comment by zzliux** [comment]
> 我找到了一个可用的auto.jspro，目前我遇到的问题是我在vscode上下载了Auto.js包，运行服务后将展示出来的连接Auto.jspro的IP地址输入到了autojspro中，目前我已经安装过依赖了npm install，我不知道我的autojspro是否已经连接上vscode，我接下来应该怎么做

@LimingEA 这个问题已经超出项目本身了，在ajpro凉了后本项目仅提供开发调试用的启动器（见release），如果非要打包的话建议先能把项目在ajpro上运行起来，如果你找的ajpro可以打包那就直接打包，不行再考虑找个别人打包好了的空白包自己手动替换里面的项目文件
