### ISSUE TITLE
autojs pro是不是跑路了？

### ISSUE THREAD

**Issue by qo0581122** [zzliux/assttyys_autojs#32]

**Comment by zzliux** [comment]
我可以这么理解吧

**Comment by qo0581122** [comment]
> 我是这么理解的

我用autojspro8代码跑不起来，请问可以提供一下可以运行的autojspro的版本吗？谢谢！

**Comment by zzliux** [comment]
realease里面的debug player可以用于调试运行本项目

**Comment by qo0581122** [comment]
> realease里面的debug player可以用于调试运行本项目

hotrun目录下执行main.js后，界面一直处于加载中，请稍后。。。没有任何的报错信息，请问一下这是为什么？

**Comment by zzliux** [comment]
> > realease里面的debug player可以用于调试运行本项目
> 
> hotrun目录下执行main.js后，界面一直处于加载中，请稍后。。。没有任何的报错信息，请问一下这是为什么？

1. 安装依赖 npm install
2. 热编译npm run start
3. 在debug player里面填写热编译运行输出的加载地址后点击加载运行

**Comment by qo0581122** [comment]
> > > realease里面的debug player可以用于调试运行本项目
> > 
> > 
> > hotrun目录下执行main.js后，界面一直处于加载中，请稍后。。。没有任何的报错信息，请问一下这是为什么？
> 
> 1. 安装依赖 npm install
> 2. 热编译npm run start
> 3. 在debug player里面填写热编译运行输出的加载地址后点击加载运行

目前报错找不到函数includes，请问一下你的node版本是多少？

**Comment by zzliux** [comment]
> > > > realease里面的debug player可以用于调试运行本项目
> > > 
> > > 
> > > hotrun目录下执行main.js后，界面一直处于加载中，请稍后。。。没有任何的报错信息，请问一下这是为什么？
> > 
> > 
> > 
> > 1. 安装依赖 npm install
> > 2. 热编译npm run start
> > 3. 在debug player里面填写热编译运行输出的加载地址后点击加载运行
> 
> 目前报错找不到函数includes，请问一下你的node版本是多少？

哪一步报错，带个截图来

**Comment by qo0581122** [comment]
> > > > > realease里面的debug player可以用于调试运行本项目
> > > > 
> > > > 
> > > > hotrun目录下执行main.js后，界面一直处于加载中，请稍后。。。没有任何的报错信息，请问一下这是为什么？
> > > 
> > > 
> > > 
> > > 1. 安装依赖 npm install
> > > 2. 热编译npm run start
> > > 3. 在debug player里面填写热编译运行输出的加载地址后点击加载运行
> > 
> > 
> > 目前报错找不到函数includes，请问一下你的node版本是多少？
> 
> 哪一步报错，带个截图来

1.npm install. 
2.npm run build. 
3.save project 
4.在autojs上执行hotrun/main.js
5.报错信息
![5691721188194_ pic](https://github.com/user-attachments/assets/39ca5e25-7dd7-43c2-9b48-6810a0200796)
6.根据报错信息修改auto.js，新增includes方法后问题解决。

node版本v20.2.0

**Comment by zzliux** [comment]
你怎么还是用hotrun运行的啊。。

**Comment by qo0581122** [comment]
> 你怎么还是用hotrun运行的啊。。

这不是想要打包编译成apk么。。。

**Comment by zzliux** [comment]
打包编译成apk也是按项目运行的，不运行hotrun，而且要修改toolAuto里面的isDebugPlayerRunning。hotrun是以前做的热更新壳用的，需自行部署服务

**Comment by qo0581122** [comment]
> isDebugPlayerRunning

了解了！谢谢！！我这边可以编译打包了
