### ISSUE TITLE
从readme里面的群号搜不到了

### ISSUE THREAD

**Issue by uukizz** [zzliux/assttyys_autojs#43]

**Comment by rqq1123** [comment]
打不开程序 白屏，应该怎么解决

**Comment by zzliux** [comment]
点击readme的群号后跳转qq可申请入群

**Comment by zzliux** [comment]
> 打不开程序 白屏，应该怎么解决

检查下webview版本，尝试下升级webview内核，更新后使用vite编译，有可能是webview版本低了
